accent = "#E742E7"
cursor = "#E742E7"
foreground = "#D4D4D4"
background = "#1E1E1E"
selection_foreground = "#1E1E1E"
selection_background = "#E742E7"

color0 = "#858585"
color1 = "#FF4949"
color2 = "#36DB36"
color3 = "#CFCF2A"
color4 = "#7E7EFF"
color5 = "#E742E7"
color6 = "#38D5D5"
color7 = "#D4D4D4"

color8 = "#858585"
color9 = "#FF4949"
color10 = "#36DB36"
color11 = "#CFCF2A"
color12 = "#7E7EFF"
color13 = "#E742E7"
color14 = "#38D5D5"
color15 = "#D4D4D4"
