accent = "#D4D4D4"
cursor = "#D4D4D4"
foreground = "#D4D4D4"
background = "#1E1E1E"
selection_foreground = "#1E1E1E"
selection_background = "#D4D4D4"

color0 = "#D4D4D4"
color1 = "#F34E4E"
color2 = "#38D5D5"
color3 = "#F34E4E"
color4 = "#E742E7"
color5 = "#CFCF2A"
color6 = "#7E7EFF"
color7 = "#36DB36"

color8 = "#D4D4D4"
color9 = "#F34E4E"
color10 = "#38D5D5"
color11 = "#F34E4E"
color12 = "#E742E7"
color13 = "#CFCF2A"
color14 = "#7E7EFF"
color15 = "#36DB36"
